This file contains the draft for cleaning.py.

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

In [2]:
fuel_price_file = 'data/data_lake/global_fuel_price.xlsx'
food_price_file = 'data/data_lake/mdg_food_price.csv'

In [3]:
gasoline_data = pd.read_excel(fuel_price_file, sheet_name="Regular Gasoline (below RON 95)")
gasoline_price = gasoline_data[gasoline_data['Country'] == 'Madagascar']

In [4]:
diesel_data = pd.read_excel(fuel_price_file, sheet_name="Diesel")
diesel_price = diesel_data[diesel_data["Diesel (LCU/liter)"] == "Madagascar"]

In [5]:
kerosene_data = pd.read_excel(fuel_price_file, sheet_name="Kerosene")
kerosene_price = kerosene_data[kerosene_data["Kerosene (LCU/liter)"] == "Madagascar"]

In [ ]:
fuel_price = pd.DataFrame()
keys_date = [date for date in gasoline_price.keys() if isinstance(date, datetime)]
fuel_price["date"] = keys_date

In [7]:
fuel_price["gasoline_price"] = gasoline_price[keys_date].values.flatten().astype(float)
fuel_price["diesel_price"] = diesel_price[keys_date].values.flatten().astype(float)
fuel_price["kerosene_price"] = kerosene_price[keys_date].values.flatten().astype(float)
fuel_price = fuel_price.ffill().bfill()
fuel_price

          date  gasoline_price  diesel_price  kerosene_price
0   2015-12-01          3640.0        3070.0          2290.0
1   2016-01-01          3640.0        3070.0          2290.0
2   2016-02-01          3640.0        3070.0          2290.0
3   2016-03-01          3640.0        3070.0          2290.0
4   2016-04-01          3640.0        3070.0          2290.0
..         ...             ...           ...             ...
108 2024-12-01          5900.0        4900.0          2430.0
109 2025-01-01          5700.0        4760.0          2430.0
110 2025-02-01          5500.0        4890.0          2630.0
111 2025-03-01          5320.0        4970.0          2830.0
112 2025-04-01          5320.0        4970.0          2830.0

[113 rows x 4 columns]

In [8]:
first_record_date = fuel_price.iloc[0]["date"]
last_record_date = fuel_price.iloc[-1]["date"]
last_record_date, first_record_date

(Timestamp('2025-04-01 00:00:00'), Timestamp('2015-12-01 00:00:00'))

In [9]:
rice_price = pd.read_csv(food_price_file)
rice_price = rice_price[rice_price["commodity"].str.contains("Rice")]
rice_price = rice_price[((rice_price["date"] >= str(first_record_date)) & (rice_price["date"] <= str(last_record_date)))]

In [10]:
# fuel_price.to_csv("data/data_warehouse/prepared_fuel_price.csv")
# rice_price.to_csv("data/data_warehouse/prepared_rice_price.csv")

In [ ]:
rice_price["date"] = pd.to_datetime(rice_price["date"])

3840    2015-12-15
3849    2015-12-15
3864    2015-12-15
3869    2015-12-15
3873    2015-12-15
           ...
16412   2025-03-15
16416   2025-03-15
16425   2025-03-15
16426   2025-03-15
16434   2025-03-15
Name: date, Length: 3357, dtype: datetime64[us]

In [24]:
rice_price["date"].sort_values().unique()

<DatetimeArray>
['2015-12-15 00:00:00', '2016-01-15 00:00:00', '2016-02-15 00:00:00',
 '2016-04-15 00:00:00', '2016-08-15 00:00:00', '2016-09-15 00:00:00',
 '2016-10-15 00:00:00', '2016-11-15 00:00:00', '2016-12-15 00:00:00',
 '2017-03-15 00:00:00', '2017-09-15 00:00:00', '2017-10-15 00:00:00',
 '2017-11-15 00:00:00', '2017-12-15 00:00:00', '2018-01-15 00:00:00',
 '2018-02-15 00:00:00', '2018-03-15 00:00:00', '2018-04-15 00:00:00',
 '2018-05-15 00:00:00', '2018-06-15 00:00:00', '2018-07-15 00:00:00',
 '2018-08-15 00:00:00', '2018-09-15 00:00:00', '2018-10-15 00:00:00',
 '2018-11-15 00:00:00', '2018-12-15 00:00:00', '2019-01-15 00:00:00',
 '2019-02-15 00:00:00', '2019-03-15 00:00:00', '2019-04-15 00:00:00',
 '2019-05-15 00:00:00', '2019-06-15 00:00:00', '2019-07-15 00:00:00',
 '2019-08-15 00:00:00', '2019-09-15 00:00:00', '2019-10-15 00:00:00',
 '2020-04-15 00:00:00', '2020-05-15 00:00:00', '2020-06-15 00:00:00',
 '2020-07-15 00:00:00', '2020-08-15 00:00:00', '2020-09-15 00:00:00',
 '2020-10-15 00:00:00', '2020-11-15 00:00:00', '2020-12-15 00:00:00',
 '2021-01-15 00:00:00', '2021-02-15 00:00:00', '2021-03-15 00:00:00',
 '2021-04-15 00:00:00', '2021-05-15 00:00:00', '2021-06-15 00:00:00',
 '2021-07-15 00:00:00', '2021-08-15 00:00:00', '2021-09-15 00:00:00',
 '2021-10-15 00:00:00', '2021-11-15 00:00:00', '2021-12-15 00:00:00',
 '2022-01-15 00:00:00', '2022-02-15 00:00:00', '2022-03-15 00:00:00',
 '2022-04-15 00:00:00', '2022-05-15 00:00:00', '2022-06-15 00:00:00',
 '2022-07-15 00:00:00', '2022-08-15 00:00:00', '2022-09-15 00:00:00',
 '2022-10-15 00:00:00', '2022-11-15 00:00:00', '2022-12-15 00:00:00',
 '2023-01-15 00:00:00', '2023-02-15 00:00:00', '2023-03-15 00:00:00',
 '2023-04-15 00:00:00', '2023-05-15 00:00:00', '2023-06-15 00:00:00',
 '2023-07-15 00:00:00', '2023-08-15 00:00:00', '2023-09-15 00:00:00',
 '2023-10-15 00:00:00', '2023-11-15 00:00:00', '2023-12-15 00:00:00',
 '2024-01-15 00:00:00', '2024-02-15 00:00:00', '2024-03-15 00:00:00',
 '2024-04-15 00:00:00', '2024-05-15 00:00:00', '2024-06-15 00:00:00',
 '2024-07-15 00:00:00', '2024-08-15 00:00:00', '2024-09-15 00:00:00',
 '2024-10-15 00:00:00', '2024-11-15 00:00:00', '2024-12-15 00:00:00',
 '2025-01-15 00:00:00', '2025-02-15 00:00:00', '2025-03-15 00:00:00']
Length: 96, dtype: datetime64[us]

In [21]:
rice_price[rice_price["date"].dt.month == 1]

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
3928,2016-01-15,Amoron I Mania,Ambositra,Amoron'I Mania (Region),760,-20.52,47.25,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1349.92,0.42
3931,2016-01-15,Analamanga,Antananarivo Renivohitra,Analamanga (Region),753,-18.93,47.52,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1470.67,0.46
3936,2016-01-15,Analanjirofo,Fenerive Est,Analanjirofo (Region),758,-17.39,49.41,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1633.17,0.51
3941,2016-01-15,Androy,Ambovombe-Androy,Androy (Region),749,-25.18,46.09,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1504.25,0.47
3947,2016-01-15,Anosy,Taolagnaro,Anosy (Region),759,-25.03,46.98,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1553.12,0.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16207,2025-01-15,Vatovavy Fitovinany,Ikongo,Ifanirea,9074,-22.19,47.48,cereals and tubers,Rice (imported),64,KG,aggregate,Retail,MGA,3150.00,0.67
16208,2025-01-15,Vatovavy Fitovinany,Ikongo,Ifanirea,9074,-22.19,47.48,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3412.50,0.73
16212,2025-01-15,Vatovavy Fitovinany,Ikongo,Ikongo,6857,-21.88,47.44,cereals and tubers,Rice (imported),64,KG,aggregate,Retail,MGA,2975.00,0.64
16213,2025-01-15,Vatovavy Fitovinany,Ikongo,Ikongo,6857,-21.88,47.44,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,2975.00,0.64
16218,2025-01-15,Vatovavy Fitovinany,Mananjary,Mananjary,8187,-21.23,48.35,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3325.00,0.71

In [28]:
rice_and_fuel_price = pd.merge_asof(
    rice_price.sort_values('date'), 
    fuel_price.sort_values('date'), 
    on='date', 
    direction='backward'
)
rice_and_fuel_price

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice,gasoline_price,diesel_price,kerosene_price
0,2015-12-15,Alaotra Mangoro,Ambatondrazaka,Alaotra Mangoro (Region),754,-17.84,48.41,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1201.67,0.38,3640.0,3070.0,2290.0
1,2015-12-15,Vatovavy Fitovinany,Manakara Atsimo,Vatovavy Fitovinany (Region),745,-22.16,48.01,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1433.33,0.46,3640.0,3070.0,2290.0
2,2015-12-15,Vakinankaratra,Antsirabe I,Vakinakaratra (Region),751,-19.87,47.04,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1353.89,0.43,3640.0,3070.0,2290.0
3,2015-12-15,Menabe,Morondava,Menabe (Region),761,-20.30,44.32,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1133.92,0.36,3640.0,3070.0,2290.0
4,2015-12-15,Diana,Antsiranana I,Diana (Region),746,-12.28,49.29,cereals and tubers,Rice (local),71,KG,actual,Retail,MGA,1404.44,0.45,3640.0,3070.0,2290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2025-03-15,Androy,Ambovombe-Androy,Ampamata,6557,-24.47,45.64,cereals and tubers,Rice (imported),64,KG,aggregate,Retail,MGA,3850.00,0.83,5320.0,4970.0,2830.0
3353,2025-03-15,Androy,Ambovombe-Androy,Ambovombe-androy,736,-25.18,46.09,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3675.00,0.79,5320.0,4970.0,2830.0
3354,2025-03-15,Vatovavy Fitovinany,Nosy-Varika,Ambodirian'I Sahafary,8175,-20.50,48.43,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3850.00,0.83,5320.0,4970.0,2830.0
3355,2025-03-15,Anosy,Betroka,Bekorobo,7206,-23.73,45.77,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3500.00,0.75,5320.0,4970.0,2830.0
3356,2025-03-15,Vatovavy Fitovinany,Nosy-Varika,Nosy Varika,6864,-20.58,48.53,cereals and tubers,Rice (local),71,KG,aggregate,Retail,MGA,3850.00,0.83,5320.0,4970.0,2830.0